2024-11-04 15:38:21,061 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'clusters']
2024-11-04 15:38:21,062 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'clusters', 'get_credentials']
2024-11-04 15:38:21,085 DEBUG    root            Running [gcloud.container.clusters.get-credentials] with arguments: [NAME: "scaling-demo"]
2024-11-04 15:38:21,088 INFO     ___FILE_ONLY___ Fetching cluster endpoint and auth data.

2024-11-04 15:38:21,090 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): container.googleapis.com:443
2024-11-04 15:38:21,333 DEBUG    urllib3.connectionpool https://container.googleapis.com:443 "GET /v1/projects/proyectotest-1/locations/europe-west1-b/clusters/scaling-demo?alt=json HTTP/1.1" 403 None
2024-11-04 15:38:21,335 DEBUG    root            (gcloud.container.clusters.get-credentials) ResponseError: code=403, message=Kubernetes Engine API has not been used in project proyectotest-1 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=proyectotest-1 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. This command is authenticated as jdiazderabago@gmail.com which is the active account specified by the [core/account] property.
Traceback (most recent call last):
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/container/api_adapter.py", line 1803, in GetCluster
    return self.client.projects_locations_clusters.Get(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/generated_clients/apis/container/v1/container_v1_client.py", line 628, in Get
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 747, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 753, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 612, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://container.googleapis.com/v1/projects/proyectotest-1/locations/europe-west1-b/clusters/scaling-demo?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Mon, 04 Nov 2024 14:38:21 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': 403}>, content <{
  "error": {
    "code": 403,
    "message": "Kubernetes Engine API has not been used in project proyectotest-1 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=proyectotest-1 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console API activation",
            "url": "https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=proyectotest-1"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "SERVICE_DISABLED",
        "domain": "googleapis.com",
        "metadata": {
          "consumer": "projects/proyectotest-1",
          "service": "container.googleapis.com"
        }
      }
    ]
  }
}
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 842, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/surface/container/clusters/get_credentials.py", line 119, in Run
    cluster, cluster_ref = _BaseRun(args, self.context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/surface/container/clusters/get_credentials.py", line 41, in _BaseRun
    cluster = adapter.GetCluster(cluster_ref)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/container/api_adapter.py", line 1812, in GetCluster
    raise exceptions.HttpException(error, util.HTTP_ERROR_FORMAT)
googlecloudsdk.calliope.exceptions.HttpException: ResponseError: code=403, message=Kubernetes Engine API has not been used in project proyectotest-1 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=proyectotest-1 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. This command is authenticated as jdiazderabago@gmail.com which is the active account specified by the [core/account] property.
2024-11-04 15:38:21,338 ERROR    root            (gcloud.container.clusters.get-credentials) ResponseError: code=403, message=Kubernetes Engine API has not been used in project proyectotest-1 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=proyectotest-1 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. This command is authenticated as jdiazderabago@gmail.com which is the active account specified by the [core/account] property.
