2024-10-30 12:42:36,568 DEBUG    root            Loaded Command Group: ['gcloud', 'app']
2024-10-30 12:42:36,886 DEBUG    root            Loaded Command Group: ['gcloud', 'app', 'deploy']
2024-10-30 12:42:36,888 DEBUG    root            Running [gcloud.app.deploy] with arguments: [--image-url: "gcr.io/practica5-1234/supermario"]
2024-10-30 12:42:37,117 DEBUG    root            Loading runtimes experiment config from [gs://runtime-builders/experiments.yaml]
2024-10-30 12:42:37,129 INFO     root            Reading [<googlecloudsdk.api_lib.storage.storage_util.ObjectReference object at 0x7f2aa0c63f10>]
2024-10-30 12:42:37,447 DEBUG    root            Flex image build option: FlexImageBuildOptions.ON_SERVER
2024-10-30 12:42:37,466 DEBUG    root            API endpoint: [https://appengine.googleapis.com/], API version: [v1]
2024-10-30 12:42:38,160 DEBUG    root            No app found:
Traceback (most recent call last):
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/app/deploy_util.py", line 818, in _PossiblyCreateApp
    return api_client.GetApplication()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/appengine_api_client.py", line 77, in GetApplication
    return self.client.apps.Get(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/generated_clients/apis/appengine/v1/appengine_v1_client.py", line 1217, in Get
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 747, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 753, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 612, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpNotFoundError: HttpError accessing <https://appengine.googleapis.com/v1/apps/practica5-1234?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'date': 'Wed, 30 Oct 2024 11:42:38 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': '404', 'content-length': '375', '-content-encoding': 'gzip'}>, content <{
  "error": {
    "code": 404,
    "message": "Resource 'projects/practica5-1234/locations/global/applications/practica5-1234' was not found",
    "status": "NOT_FOUND",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ResourceInfo",
        "resourceName": "projects/practica5-1234/locations/global/applications/practica5-1234"
      }
    ]
  }
}
>
2024-10-30 12:42:38,174 INFO     ___FILE_ONLY___ You are creating an app for project [practica5-1234].

2024-10-30 12:42:38,174 WARNING  root            Creating an App Engine application for a project is irreversible and the region
cannot be changed. More information about regions is at
<https://cloud.google.com/appengine/docs/locations>.

2024-10-30 12:43:07,416 INFO     ___FILE_ONLY___ 

Command killed by keyboard interrupt


